export interface Country {
  id: string;
  name: string;
  slug: string;
  image: string;
  video?: string;
  visaType: string;
  processingTime: string;
  description: string;
  price: number;
  rating?: string;
  processing?: string;
  visaCategories?: string[];
  approvalRate?: string;
  popular?: boolean;
  featured?: boolean;
  visasProcessed?: string;
}

export interface Service {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export interface VisaCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  duration: string;
  price: number;
}

export interface Testimonial {
  name: string;
  location: string;
  text: string;
  rating: number;
  image?: string;
}

export const countries: Country[] = [
  {
    id: "usa",
    name: "United States",
    slug: "united-states",
    image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80",
    visaType: "B1/B2 Tourist & Business",
    processingTime: "3-5 working days",
    description: "Expert guidance for US tourist, business, and student visa applications.",
    price: 18500,
    approvalRate: "95%",
    popular: true,
    featured: true,
    visasProcessed: "17K+",
  },
  {
    id: "uk",
    name: "United Kingdom",
    slug: "united-kingdom",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80",
    visaType: "Standard Visitor Visa",
    processingTime: "10-15 working days",
    description: "Streamlined UK visa processing with document review and interview prep.",
    price: 16000,
    approvalRate: "93%",
    popular: true,
    featured: true,
    visasProcessed: "16K+",
  },
  {
    id: "canada",
    name: "Canada",
    slug: "canada",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?w=800&q=80",
    visaType: "Visitor & Study Permit",
    processingTime: "12-20 working days",
    description: "Complete support for Canadian visitor visas and study permits.",
    price: 12000,
    approvalRate: "92%",
    popular: true,
    featured: true,
    visasProcessed: "10K+",
  },
  {
    id: "australia",
    name: "Australia",
    slug: "australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
    visaType: "Subclass 600 Visitor",
    processingTime: "10-18 working days",
    description: "End-to-end Australia visa assistance with high approval rates.",
    price: 14000,
    approvalRate: "94%",
    popular: true,
    featured: true,
    visasProcessed: "92K+",
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    slug: "new-zealand",
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80",
    visaType: "Visitor Visa",
    processingTime: "15-25 working days",
    description: "Expert guidance for New Zealand visitor and student visas.",
    price: 11000,
    approvalRate: "91%",
    popular: true,
    featured: true,
    visasProcessed: "15K+",
  },
  {
    id: "schengen",
    name: "Schengen (Europe)",
    slug: "schengen",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80",
    visaType: "Schengen Visa",
    processingTime: "7-15 working days",
    description: "Schengen visa expertise for 27 European countries from a single application.",
    price: 11000,
    approvalRate: "90%",
    popular: true,
    featured: true,
    visasProcessed: "25K+",
  },
  {
    id: "uae",
    name: "United Arab Emirates",
    slug: "uae",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    visaType: "Tourist & Transit",
    processingTime: "3-5 working days",
    description: "Fast-track UAE tourist and transit visa processing services.",
    price: 7500,
    approvalRate: "98%",
    popular: true,
    featured: true,
    visasProcessed: "15K+",
  },
  {
    id: "japan",
    name: "Japan",
    slug: "japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    visaType: "Short-Term Stay",
    processingTime: "5-10 working days",
    description: "Japan visa guidance including documentation and embassy coordination.",
    price: 9000,
    approvalRate: "93%",
    popular: true,
    featured: true,
    visasProcessed: "92K+",
  },
  {
    id: "singapore",
    name: "Singapore",
    slug: "singapore",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    visaType: "Tourist Visa",
    processingTime: "3-7 working days",
    description: "Quick Singapore visa applications with personalized consultation.",
    price: 6000,
    approvalRate: "96%",
    popular: true,
    featured: true,
    visasProcessed: "12K+",
  },
  {
    id: "south-korea",
    name: "South Korea",
    slug: "south-korea",
    image: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "5-12 working days",
    description: "Comprehensive South Korea visa assistance for tourism and business.",
    price: 7000,
    approvalRate: "92%",
    popular: true,
    featured: true,
    visasProcessed: "5K+",
  },
  {
    id: "vietnam",
    name: "Vietnam",
    slug: "vietnam",
    image: "https://images.unsplash.com/photo-1548048026-5a1a941d93d3?w=800&q=80",
    visaType: "E-Visa & Tourist Visa",
    processingTime: "3-5 working days",
    description: "Fast Vietnam e-visa and tourist visa processing services.",
    price: 4000,
    approvalRate: "97%",
    popular: true,
    featured: true,
    visasProcessed: "12K+",
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    slug: "saudi-arabia",
    image: "https://images.unsplash.com/photo-1590402494582-2c6f297b6a8d?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "2-5 working days",
    description: "Quick Saudi Arabia visa processing including Umrah and business visas.",
    price: 8500,
    approvalRate: "95%",
    popular: true,
    featured: true,
    visasProcessed: "12K+",
  },
  {
    id: "thailand",
    name: "Thailand",
    slug: "thailand",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80",
    visaType: "Tourist Visa",
    processingTime: "3-6 working days",
    description: "Efficient Thailand visa processing for tourism and business.",
    price: 4500,
    approvalRate: "96%",
    popular: true,
    featured: true,
    visasProcessed: "1K+",
  },
  {
    id: "turkey",
    name: "Turkey",
    slug: "turkey",
    image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
    visaType: "E-Visa & Tourist Visa",
    processingTime: "2-4 working days",
    description: "Fast Turkey e-visa service with easy online application process.",
    price: 5000,
    approvalRate: "97%",
    popular: true,
    featured: false,
    visasProcessed: "16K+",
  },
  {
    id: "malaysia",
    name: "Malaysia",
    slug: "malaysia",
    image: "https://images.unsplash.com/photo-1595223262681-34a99977985a?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "3-7 working days",
    description: "Efficient Malaysia visa processing with high approval rates.",
    price: 5000,
    approvalRate: "96%",
    popular: false,
    featured: false,
    visasProcessed: "92K+",
  },
  {
    id: "indonesia",
    name: "Indonesia",
    slug: "indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "4-8 working days",
    description: "Complete Indonesia visa services for tourism, business, and more.",
    price: 5500,
    approvalRate: "94%",
    popular: false,
    featured: false,
    visasProcessed: "90K+",
  },
  {
    id: "egypt",
    name: "Egypt",
    slug: "egypt",
    image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
    visaType: "E-Visa & Tourist Visa",
    processingTime: "3-7 working days",
    description: "Egypt visa services for tourism and business travelers.",
    price: 4500,
    approvalRate: "95%",
    popular: false,
    featured: false,
    visasProcessed: "8K+",
  },
  {
    id: "kenya",
    name: "Kenya",
    slug: "kenya",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    visaType: "E-Visa",
    processingTime: "2-5 working days",
    description: "Kenya e-visa services for tourism, business, and transit.",
    price: 4000,
    approvalRate: "96%",
    popular: false,
    featured: false,
    visasProcessed: "15K+",
  },
  {
    id: "south-africa",
    name: "South Africa",
    slug: "south-africa",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "10-20 working days",
    description: "South Africa visa assistance for tourism and business purposes.",
    price: 8000,
    approvalRate: "89%",
    popular: false,
    featured: false,
    visasProcessed: "2K+",
  },
  {
    id: "brazil",
    name: "Brazil",
    slug: "brazil",
    image: "https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "7-15 working days",
    description: "Brazil visa support for tourism, business, and cultural exchange.",
    price: 9000,
    approvalRate: "88%",
    popular: false,
    featured: false,
    visasProcessed: "3K+",
  },
  {
    id: "russia",
    name: "Russia",
    slug: "russia",
    image: "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "10-20 working days",
    description: "Russian visa services including invitation letter support.",
    price: 8500,
    approvalRate: "87%",
    popular: false,
    featured: false,
    visasProcessed: "4K+",
  },
  {
    id: "china",
    name: "China",
    slug: "china",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "7-14 working days",
    description: "China visa processing for tourism, business, and transit.",
    price: 10000,
    approvalRate: "90%",
    popular: false,
    featured: false,
    visasProcessed: "8K+",
  },
  {
    id: "philippines",
    name: "Philippines",
    slug: "philippines",
    image: "https://images.unsplash.com/photo-1559592413-7cec48d8b7a8?w=800&q=80",
    visaType: "Tourist Visa",
    processingTime: "5-10 working days",
    description: "Philippines visa processing for tourism and business travelers.",
    price: 4000,
    approvalRate: "95%",
    popular: false,
    featured: false,
    visasProcessed: "6K+",
  },
  {
    id: "sri-lanka",
    name: "Sri Lanka",
    slug: "sri-lanka",
    image: "https://images.unsplash.com/photo-1560834947-2e6e204c5e5e?w=800&q=80",
    visaType: "E-Visa & Tourist Visa",
    processingTime: "2-4 working days",
    description: "Quick Sri Lanka e-visa processing for tourism and business.",
    price: 3500,
    approvalRate: "98%",
    popular: false,
    featured: false,
    visasProcessed: "14K+",
  },
  {
    id: "nepal",
    name: "Nepal",
    slug: "nepal",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    visaType: "Tourist Visa",
    processingTime: "1-3 working days",
    description: "Nepal tourist visa services with easy on-arrival processing guidance.",
    price: 2500,
    approvalRate: "99%",
    popular: false,
    featured: false,
    visasProcessed: "10K+",
  },
  {
    id: "bangladesh",
    name: "Bangladesh",
    slug: "bangladesh",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    visaType: "Tourist & Business Visa",
    processingTime: "5-10 working days",
    description: "Bangladesh visa processing for tourism and business purposes.",
    price: 3500,
    approvalRate: "94%",
    popular: false,
    featured: false,
    visasProcessed: "5K+",
  },
  {
    id: "qatar",
    name: "Qatar",
    slug: "qatar",
    image: "https://images.unsplash.com/photo-1624628638876-79d2ee5c17b9?w=800&q=80",
    visaType: "Tourist & Transit Visa",
    processingTime: "2-5 working days",
    description: "Qatar visa services for tourism, transit, and business visits.",
    price: 5000,
    approvalRate: "95%",
    popular: false,
    featured: false,
    visasProcessed: "1K+",
  },
  {
    id: "oman",
    name: "Oman",
    slug: "oman",
    image: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80",
    visaType: "Tourist & Transit Visa",
    processingTime: "2-5 working days",
    description: "Oman visa services for tourism and transit travelers.",
    price: 5000,
    approvalRate: "96%",
    popular: false,
    featured: false,
    visasProcessed: "6K+",
  },
  {
    id: "azerbaijan",
    name: "Azerbaijan",
    slug: "azerbaijan",
    image: "https://images.unsplash.com/photo-1627492472849-d68ed1ae98cb?w=800&q=80",
    visaType: "E-Visa",
    processingTime: "3-5 working days",
    description: "Fast Azerbaijan e-visa processing for tourism and business.",
    price: 3000,
    approvalRate: "97%",
    popular: false,
    featured: false,
    visasProcessed: "68K+",
  },
  {
    id: "cambodia",
    name: "Cambodia",
    slug: "cambodia",
    image: "https://images.unsplash.com/photo-1579332671787-c713e6f02f54?w=800&q=80",
    visaType: "E-Visa & Tourist Visa",
    processingTime: "3-5 working days",
    description: "Cambodia e-visa and tourist visa processing services.",
    price: 3500,
    approvalRate: "97%",
    popular: false,
    featured: false,
    visasProcessed: "10K+",
  },
];

export const sourceCountries = [
  "Afghanistan", "Albania", "Algeria", "Angola", "Argentina", "Armenia",
  "Australia", "Azerbaijan", "Bahrain", "Bangladesh", "Belarus", "Benin",
  "Bolivia", "Botswana", "Brazil", "Bulgaria", "Burkina Faso", "Burundi",
  "Cambodia", "Cameroon", "Canada", "Chad", "Chile", "China", "Colombia",
  "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Estonia", "Ethiopia", "Finland", "France", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Greece", "Guatemala", "Guinea", "Haiti", "Honduras",
  "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
  "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon",
  "Libya", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia",
  "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico",
  "Moldova", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
  "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saudi Arabia",
  "Senegal", "Serbia", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan",
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan",
  "Tanzania", "Thailand", "Togo", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Venezuela",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe",
];

export const destinationCountries = sourceCountries;

export const services: Service[] = [
  {
    id: "consultation",
    title: "Free Consultation",
    description: "One-on-one sessions with certified visa consultants to assess your eligibility.",
    icon: "MessageCircle",
  },
  {
    id: "documentation",
    title: "Document Preparation",
    description: "Complete document checklist, review, and formatting to meet embassy standards.",
    icon: "FileText",
  },
  {
    id: "application",
    title: "Application Filing",
    description: "End-to-end application submission with real-time tracking and status updates.",
    icon: "Send",
  },
  {
    id: "interview",
    title: "Interview Coaching",
    description: "Mock interviews and personalized coaching to boost your visa approval chances.",
    icon: "Users",
  },
  {
    id: "express",
    title: "Express Processing",
    description: "Priority handling for urgent travel with expedited document processing.",
    icon: "Zap",
  },
  {
    id: "support",
    title: "24/7 Support",
    description: "Round-the-clock assistance via phone, email, and live chat for all queries.",
    icon: "Headphones",
  },
];

export const visaCategories: VisaCategory[] = [
  {
    id: "tourist",
    title: "Tourist Visa",
    description: "Explore the world with hassle-free tourist visa processing.",
    icon: "Plane",
    duration: "Up to 90 days",
    price: 5000,
  },
  {
    id: "business",
    title: "Business Visa",
    description: "Attend meetings, conferences, and trade events globally.",
    icon: "Briefcase",
    duration: "Up to 180 days",
    price: 8000,
  },
  {
    id: "student",
    title: "Student Visa",
    description: "Pursue education abroad with complete study visa support.",
    icon: "GraduationCap",
    duration: "Course duration",
    price: 10000,
  },
  {
    id: "work",
    title: "Work Visa",
    description: "Secure employment visas with employer sponsorship guidance.",
    icon: "Building2",
    duration: "1–5 years",
    price: 15000,
  },
  {
    id: "family",
    title: "Family Visa",
    description: "Reunite with loved ones through family reunion visa programs.",
    icon: "Heart",
    duration: "Varies",
    price: 12000,
  },
  {
    id: "transit",
    title: "Transit Visa",
    description: "Quick transit visa solutions for layovers and connecting flights.",
    icon: "ArrowRightLeft",
    duration: "Up to 72 hours",
    price: 3000,
  },
];

export const stats = [
  { label: "Visas Processed", value: "50,000+" },
  { label: "Countries Served", value: "120+" },
  { label: "Success Rate", value: "98%" },
  { label: "Years Experience", value: "15+" },
];

export const testimonials: Testimonial[] = [
  {
    name: "Priya Sharma",
    location: "Mumbai, India",
    text: "I was nervous about my US visa application, but the team at travelPaa made the process incredibly smooth. They reviewed every document and prepared me thoroughly for the interview. Got my visa approved without any issues!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
  },
  {
    name: "Ahmed Hassan",
    location: "Dubai, UAE",
    text: "Applied for a Schengen visa through travelPaa and was impressed by their professionalism. The document checklist was comprehensive and they caught a few errors I would have missed. Highly recommended.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
  },
  {
    name: "Sarah Johnson",
    location: "London, UK",
    text: "Excellent service for my Australian student visa. The team guided me through the entire process from university selection to visa application. My visa was approved in just 2 weeks!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
  },
  {
    name: "Rajesh Patel",
    location: "Ahmedabad, India",
    text: "I've used travelPaa for three different visa applications and each time they've exceeded expectations. Their knowledge of different countries' requirements is outstanding.",
    rating: 4,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
  },
  {
    name: "Yuki Tanaka",
    location: "Tokyo, Japan",
    text: "The Canada visitor visa process seemed daunting, but travelPaa broke it down into simple steps. Their consultant was always available to answer my questions. Very grateful for their support.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&q=80",
  },
  {
    name: "Omar Al-Rashid",
    location: "Riyadh, Saudi Arabia",
    text: "Fast and reliable service for my UK business visa. The invitation letter template they provided was perfect. Visa was approved within 10 days. Will definitely use them again.",
    rating: 4,
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80",
  },
];
